version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm

    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh:/home/vscode/.ssh

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - default
      - mongodb

    depends_on:
      - db

  
  db:
    image: mongo
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: fizzbuzz
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    
    networks:
      - mongodb

    ports:
      - 27017:27017

    volumes:
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


volumes:
  mongodbdata:

networks:
  mongodb:
